name: radio_house
description: Radio player app for LabHouse
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  build_runner: ^2.4.9
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_loggy_dio: ^3.1.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  hooks_riverpod: ^3.0.0-dev.3
  injectable: ^2.4.1
  injectable_generator: ^2.6.1
  intl: ^0.19.0
  loggy: ^2.0.3
  path: ^1.9.0
  radio_player: ^1.5.1
  rive: ^0.13.5
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  riverpod_lint: ^3.0.0-dev.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true